stages:
  - init
  - test
  - finish

.base:
  before_script:
    - schutzbot/ci_details.sh > ci-details-before-run
    - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
  after_script:
    - schutzbot/ci_details.sh > ci-details-after-run || true
    - schutzbot/update_github_status.sh update || true
  interruptible: true
  tags:
    - terraform
  artifacts:
    paths:
      - ci-artifacts
      - ci-details-before-run
      - ci-details-after-run
      - "*.repo"
    when: always

.terraform:
  extends: .base
  tags:
    - terraform


init:
  stage: init
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh start
  interruptible: true

Manifests:
  stage: test
  extends: .terraform
  script:
    - schutzbot/deploy.sh
    - sudo schutzbot/selinux-context.sh
    - sudo test/cases/manifest_tests
  artifacts:
    when: always
    paths:
      - generated-image-infos/
  parallel:
    matrix:
      - RUNNER:
          - aws/fedora-35-aarch64

finish:
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - schutzbot/update_github_status.sh finish
