name: Checks

on: [pull_request, push]

jobs:
  codespell:
    name: "Spell check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: msdos, pullrequest
          skip: ./.git

  checks:
    name: "Python check"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          path: manifest-db

      - name: Check files with mypy
        run: |
          sudo apt install python3-pip -y
          sudo pip install mypy
          sudo pip install types-PyYAML
          for i in manifest-db/tools/*; do mypy --ignore-missing-imports "${i}"; done
          for i in manifest-db/test/cases/*; do mypy --ignore-missing-imports "${i}"; done
